### ISSUE TITLE
Typescript `APIGatewayProxyHandler` interface is now incorrect

### ISSUE THREAD

**Issue by ghost** [sweeetland/lambda-hooks#6]
Hi, I'm new to serverless and you did a great utility tool right there, Thanks :+1: 

However, I have an issue with the `parseEvent` hook. 

Usually, I define my functions like so :

```
import { APIGatewayProxyHandler, APIGatewayProxyResult } from "aws-lambda";
import "source-map-support/register";
import { withHooks, IPayload } from "../common";

const function: APIGatewayProxyHandler = async (event, _context) => {
  
  // => Throws a type error since my `IPayload` interface can't be  inferred from a `string` 
  // type (even though it's not actually a string thanks to the `parseEvent` hook)
  const payload: IPayload[] = event.body; 

  // do some magic...

  return <APIGatewayProxyResult>{
    statusCode: 200,
    body: JSON.stringify(data),
  };
};

exports.function = withHooks(function);
```

Basically, since the `parseEvent` modifies the event types (e.g: `event.body: string,` to `event.body: any` because of the JSON.parse), we can't use the `APIGatewayProxyHandler` interface anymore.

Here's a dirty workaround I'm using for now : 

```
const payload: IPayload[] = <IPayload[]>(<unknown>event.body);
```

Should we make a custom event interface based on the `parseEvent` function or is there a better solution ?

**Comment by sweeetland** [comment]
Hey @crouinicrouina,

Thanks for the kind words. I created another package because I experienced this exact problem.

You can find the src code at the link below as unfortunately I haven't got round to writing the readme yet...

[github.com/sweeetland/better-lambda-types](https://github.com/sweeetland/better-lambda-types)

And you can see an example of how to use here at this file [here](https://github.com/sweeetland/production-ready-serverless/blob/master/src/api/hello.ts).

Please let me know if you need further clarification :)

**Comment by ghost** [comment]
Hi @sweeetland,

Thank you very much for these snippets, they are really useful, I appreciate it :+1: 

I'd love to help with PRs but unfortunately, I don't have enough time :(

Anyways, I wish you good luck for the future and thanks again !
